# Generated by Django 3.1.4 on 2021-02-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('coding', 'coding'), ('sport', 'sport'), ('books', 'books')], default=1, max_length=225),
            preserve_default=False,
        ),
    ]
