# Generated by Django 3.1.4 on 2021-02-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20210223_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='sport', max_length=255),
        ),
    ]
